/**
 * @author Jean-Aymeric DIET jadiet@cesi.fr
 * @version 1.0
 */
package model;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

// TODO: Auto-generated Javadoc
/**
 * The Class ModelTest.
 */
public class ModelTest {
    
    /** The model. */
    private Model model;

    /**
     * Sets the up before class.
     *
     * @throws Exception the exception
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
    }

    /**
     * Tear down after class.
     *
     * @throws Exception the exception
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
    }

    /**
     * Sets the up.
     *
     * @throws Exception the exception
     */
    @Before
    public void setUp() throws Exception {
        this.model = new Model();
    }

    /**
     * Tear down.
     *
     * @throws Exception the exception
     */
    @After
    public void tearDown() throws Exception {
    }

    /**
     * Test get message.
     */
    @Test
    public void testGetMessage() {
        Assert.assertEquals("", this.model.getLevel().getMessage());
    }

    /**
     * Test get message string.
     */
    @Test
    public void testGetMessageString() {
        this.model.loadLevel(1);
        Assert.assertEquals("UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU;UDDDDDDRDDDDDDDDDDDDDRDDDDDDDU;UDDSDDDDDRDDDDDDDDDDDRDDODDDDU;UDDDDDDDDDDDDDDDDDDDDDDRDDDDDU;UDDDDDDDDDDDODDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDRDDDDDDDDDDDU;UDDDORDDDDDDDDDDDDDDDDDDDODDDU;UDDDDDDDDDDDDDDDDDDDDRRDDDDDDU;UBBBBBDDBBBBBBDBBBBBBDDBBBBBBU;UDDDRDDDDDDDDRDDDDDDDDDDDDODDU;UDDDDDDODDDDDDDDDDRDDDDDDDDDDU;UDDDDDDDDDDDDRDDDDODDDDDDDDDDU;URDDDDDDDDDDDDDDDDDDDDDRDDDDDU;UBBBBBBBBBBBBBBBBBBBBBBBBBRDDU;UDDDDRDDDDDDDDDDRDDDODDDDDDDDU;UDDDDODDDDRDDDDDDDDDDDDRDDDDDU;UDRDDDDDDDRDDDDDDDDDDRDDDDDDDU;UDDDDDDDDDDDRDDODDDDDDDDDDDODU;UDDBBBBBBBBBBBBBBBBBBBBBBBBBBU;UDDDRDODDDDDDDDDRDDDDDDDDDDDDU;UDDDRDDDDDDDDDDDDRDDDDDDRODDDU;UDDDRDDDDDDDDRDDDDDDDDDDDDDDDU;UDDDDDDDDDDRDODDDDDDDDRDDDDDDU;UBBBBBBBBBBBBBBBBBBBBBBBBBBDDU;UDODDDDDDDDDDDDDDDDDODDRDDDDDU;UDDDDRDDDDDRDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDODDDRDDDDDDDDDDDDDU;UOEDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDRDDDDDDDDDRDDODDDRDDDU;UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", this.model.getLevel().getMessage());
        this.model.loadLevel(2);
        Assert.assertEquals("UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU;UDDDDDDODDDDDDDDDDDODDDDDDDDDU;UDDSDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDODDDDDDDDDDODDDDU;UBBBBBDDDBBBBBDDBBBBBDDDBBBBBU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDMCCMCDDMCCMCDDCMCCMDDCMCCMDU;UDCCCCCDDCCCCCDDCCCCCDDCCCCCDU;UDCCOCCDDCCOCCDDCCOCCDDCCOCCDU;UDCCDCCDDCCDCCDDCCDCCDDCCDCCDU;UDCCCCCDDCCCCCDDCCCCCDDCCCCCDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UBBBBBDDDBBBBBDDBBBBBDDDBBBBBU;UDDDDDDDRDDDODDDDDRDDODDDDDRDU;UDDRDODDDDDDDDDDDDRODDDDDDDDDU;UBBBBBDDDBBBBBDDBBBBBDDRBBBBBU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDMCCMCDDMCMCCDDMCMCCDDMCCMCDU;UDCCCCCDDCCCCCDDCCCCCDDCCCCCDU;UDCCOCCDDCCOCCDDCCOCCDRCCOCCDU;UDCCDCCDRCCDCCDDCCDCCDDCCDCCDU;UDCCCCCDDCCCCCDDCCCCCDDCCCCCDU;UDDDDDDDDRDDDDDDDDDDDDDDDDDDDU;UBBBBBDDDBBBBBDDBBBBBDDRBBBBBU;UDDRDDDDDDDRDDDDDDDDDDDDODDRDU;UDODDDDDDODDDDDDDDDRDDDDRDDDDU;UDDDDDRDDDDDDDEDDDRDDDDDDRDDDU;UDDDRDDDDDDDDODDDDDDDDDDDRDDDU;UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", this.model.getLevel().getMessage());
        this.model.loadLevel(3);
        Assert.assertEquals("UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU;UDDDDDDSDUDEDDDDDDDDDDDDDDDDDU;UDUUUUUUUUUUUUUUUUUUUUUUUUUUDU;UDUDDDDDDDDDDDDDDDDUDDDDDDDUDU;UDUOUUUUUUUDUUUUUUUUDUUUUUDUDU;UDUUUDDDDDDDDDDDDDDUDDDDDUDDDU;UDDDUDUUUUUUUUUUUUDUUUUDDUUUDU;UDUDUDUDDDDDDDDDDDDDDDUDDDDUDU;UDUOUDUDUUUUUUUUUUUUUUUUUDDUDU;UDUUUDUDUDDDDDDDDDDDDDDDUDDUDU;UDUDUDUDUUUUUDDUDDUUUUUDUDDUDU;UDDDDDUDUDDDDDDDDDDDDDUDUDDUDU;UDUUUUUDDDDDDDDDDDDDDDUDUDDUDU;UDUODDDDUDDDDDDODDDDDDUDDDDUDU;UDUUUUUUUDDODDDDDDDDDDUUUDDUOU;UOUDDDDDUUUUUUUUUUUUUUUOUDDUUU;UUUDDDDDDDDDDDDDDDDDDUDDUDDUOU;UDDODRDDDDDDDDDDDDRDDUDDUDDUDU;UDDDDDDDDDDDDRDDDDDDDUDDUDDUDU;UDRDDDDDDDDDRDDDDDODDDDDUDDUDU;UDDDRDDDDDDDRDDDDDDDDUDDUDDUDU;UUUUUUUUDDDDDDDDDDDDDUDDUDDUDU;UDDDUDDRDDDDRDDDRDDDDUDDUDDUDU;UDUDUDDDDDDDDDDDDDDUUUDDUDDUDU;UDUDUDRDDDDDDDDODDDDUDDDUDDUDU;UDUDUUUUUUUUDUUUUUUUDDUUUDDUDU;UDUDDDDDDDOUDUODDDDDDDUDDDDUDU;UDUUUUUUUUUUDUUUUUUUUUUDUUUUDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", this.model.getLevel().getMessage());
        this.model.loadLevel(4);
        Assert.assertEquals("UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU;USDDDDDDDDDDDDDDRDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDRDDDDDDU;UDDDDRDDDDDDRDDDDDDDDDDDDDDDDU;UDDDDRDDDDDDRDDDDDDRDDDDRDDDDU;UDDDDDDRDDDDDRDDDDDDDDRDDDDDDU;UDDDDDDDDDDDDDDDDDDDRDDDDDDDDU;UDDRDDDDDDDDDDDDDDDDDDDDDDDRDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDCCCMDDDDCMCCRDDDMCCCDDDDU;UDDDDCCCCDRDDCCCCDDDDCCCCDDDDU;UDRDDDDDDDDDDDDDDDDRDDDDDDDDDU;UDDRDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDRDDDDDDDDDDDDDRDDDDDDDU;UDDDDDDDDRDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDRDDRDDDDDRDDRDDDDDDU;UDRDDDRDDDRDDDDDDDRDRDDRDDDDDU;UDDDDDDDRDDDDDDRDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDCMCCMCDDDDDDMCCCMCCDDDDU;UDDDDDCCCCCCDDDDDDCCCCCCCDDDDU;UBBBBBBBBBBBBBBBBBBBBBBBBBBBBU;UDDDDDDDDRDDDDDRDDDDDDDDRDDDDU;UDDRDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDRDDDDDDDDDDDDDDDDDRDDDDU;UDDDDDDDDDDDDDDDDDDRDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDRDDDDDDDDDDDDDDDDDDDEU;UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", this.model.getLevel().getMessage());
        this.model.loadLevel(5);
        Assert.assertEquals("UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU;UDDDDDORBDDDDDDDDDDDDDDDDDDDDU;USDDDDDDDDDDDDDDDDDDDDODDDDDDU;UBBBBBBBBBBBBDDDDDODDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDODDDDDDDODDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDCMCCCCCCCCDCMCCDCCCCCCCCMCDU;UDCCCCCCCCCCDCCCCDCCCCCCCCCCDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDRDDDDDDDRDDDRDDDDDDRDDDDU;UBBBBBDDDBBBBBDDDBBBBBDDBBBBBU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDDDDDDDDDDDDDDDDDDDDDDDDDDDDU;UDCCCCCCCCCMCCDDCCCCCCCCMCCCCU;UDCCCCCCCCCCCCDDCCCCCCCCCCCCCU;UBBBBBBBBBBBBBBBBBBBBBBBBBBBBU;UDRDDDDDDDDDDDDDDDDDRDDDDDDDDU;UDDDDDRDDDDDDDDDDDDBDDDDDDDDDU;UDDDBBBBBBBBBBBBBBBBBBBBBBBBBU;UDDDDDDRBDDDDDDDDODDDDDDDDODDU;UDDDDDDODDDDDDDDDDBDDDDDDDDDDU;UBBBBBBBBBBBBBBBBBBBBBBBBBBDDU;UEDDDDDDODDDDDDDODDDDDDDDDDDDU;UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU", this.model.getLevel().getMessage());
    }
}
